### ISSUE TITLE
Modbus设置-设备列表的默认规则和重复检测

### ISSUE THREAD

**Issue by srdgame** [thingsroot/webSpecialGateway#1]
1. 地址
* 默认值为当前列表中最大的地址 + 1, 如果表格为空，第一个设备的地址默认为1
* 无重复检测（即地址可以相同)
2. 设备名称
* 默认值为 <通道名称>.device<默认地址>
* 重复检测
3. 设备序列号
* 默认值为<通道名称>_<默认地址>
* 重复检测 (全网关重复检测)

重复检测问题：
1. 当设备序列号重复时，重复提示却出现在了其他列上,  而且修正后提示依然还在。如图所示：

![image](https://user-images.githubusercontent.com/54447/65654145-5fbe0080-e04a-11e9-9845-b1795ba88209.png)

![image](https://user-images.githubusercontent.com/54447/65654483-934d5a80-e04b-11e9-9875-581a32338157.png)
![image](https://user-images.githubusercontent.com/54447/65654511-b0822900-e04b-11e9-937a-0535eb82edaf.png)

输入问题：
用户输出经常会被打断（输入控件在接收到一个字符的输入后，失去了焦点)  。

输入完成后，输入框并没有消失

![image](https://user-images.githubusercontent.com/54447/65654604-035be080-e04c-11e9-8432-9de2b8822e22.png)

**Comment by onlyH** [comment]
cf5fdef287de8d5cb358bb5a6cb9a54b872c87df

**Comment by a980263316** [comment]
设备序列号没有全网关检测，当设备列表SN与其他Mosbus应用设备列表SN重复时未检测

**Comment by onlyH** [comment]
设备序列号全网关检测 comment 2eb7b3d002f5e0a082d87ea96365ff8c2a6ab89d
