### ISSUE TITLE
Modbus配置：通讯类型是串口时，向应用post的值有误

### ISSUE THREAD

**Issue by viccom** [thingsroot/webSpecialGateway#22]
通讯类型是串口时，需要将COM1，COM2这样的值进行转换。
如型号是T1-3000，对应关系：
{
“COM1”:"/dev/ttyS1",
“COM2”:"/dev/ttyS2",
}
如型号是Q102，对应关系：
{
“COM1”:"/dev/ttymxc0",
“COM2”:"/dev/ttymxc1",
}
如型号是Q204，对应关系：
{
“COM1”:"/dev/ttymxc0",
“COM2”:"/dev/ttymxc1",
“COM3”:"/dev/ttymxc2",
“COM4”:"/dev/ttymxc3",
}

**Comment by onlyH** [comment]
cf5fdef287de8d5cb358bb5a6cb9a54b872c87df

**Comment by onlyH** [comment]
cf5fdef287de8d5cb358bb5a6cb9a54b872c87df
