### ISSUE TITLE
MQTT配置：高级选项开启后，勾选了禁止数据上送，MQTT broker

### ISSUE THREAD

**Issue by viccom** [thingsroot/webSpecialGateway#33]
高级选项开启后，勾选了禁止数据上送，MQTT broker还是能收到数据。
![image](https://user-images.githubusercontent.com/11530494/65811486-84051300-e1eb-11e9-87e0-842758391e34.png)
高级选项中禁止数据上送选项，是禁止网关向MQTT Broker上送任何数据的意思吗？

**Comment by srdgame** [comment]
字段应该是disable_data 而不是diable_data
