### ISSUE TITLE
Modbus设置-串口端口要有默认值

### ISSUE THREAD

**Issue by srdgame** [thingsroot/webSpecialGateway#5]
串口端口要有默认值，而不是"请选择"

**Comment by srdgame** [comment]
串口重复检测，即串口只能被一个通道所使用。当另外的通道选择已经被使用的串口时，要提示。 （或者直接从dropdown里面删除已经被占用的串口)

**Comment by srdgame** [comment]
当串口1、串口2都被使用后，串口依然可以选择 COM2

**Comment by onlyH** [comment]
cf5fdef287de8d5cb358bb5a6cb9a54b872c87df
